// data/session
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SIGNUP_PENDING = 'SIGNUP_PENDING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// ui/test-ui
export const OFF = 'OFF';
export const ON = 'ON';

// ui/new-task
export const NEW_TASK_PAGE_TRANSITION_PENDING = 'NEW_TASK_PAGE_TRANSITION_PENDING';
export const NEW_TASK_PAGE_TRANSITION_COMPLETE = 'NEW_TASK_PAGE_TRANSITION_COMPLETE';

// ui/tasks-list
export const TASKS_LIST_PAGE_TRANSACTION_PENDING = 'TASKS_LIST_PAGE_TRANSACTION_PENDING';
export const TASKS_LIST_PAGE_TRANSACTION_COMPLETE = 'TASKS_LIST_PAGE_TRANSACTION_COMPLETE';

// data/tasks
export const FETCH_TASKS_PENDING = 'FETCH_TASKS_PENDING';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_ERROR = 'FETCH_TASKS_ERROR';
export const SET_TASKS = 'SET_TASKS';
export const ADD_TASK = 'ADD_TASK';